version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: probo-api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - CONFIG_PATH=config/docker.yaml  # I am not pushing config file into the github and dockerhub

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: redis
    restart: always

volumes:
  pgdata: